services:
  novnc: # Service for displaying X11 applications from containers (use on macOS hosts)
    image: theasp/novnc:latest
    environment:
      - DISPLAY_WIDTH=1024
      - DISPLAY_HEIGHT=768
      - RUN_XTERM=no
    ports:
      - "8080:8080"
    networks:
      - x11

networks:
  x11:
